#!/usr/bin/env python3
import asyncio
from tcp import Servidor
import re

conexao.dados_residuais = b'' 

def validarnome(nome):
    return re.match(br'^[a-zA-Z][a-zA-Z0-9-]*$', nome) is not None


def sair(conexao):
    print(conexao, 'conexão fechada')
    conexao.fechar()


def dados_recebidos(conexao, dados):
    if dados == b'':
        return sair(conexao)
    if not dados.endswith(b'\n'):
        conexao.dados_residuais = conexao.dados_residuais + dados
    else:
        if conexao.dados_residuais != b'':
            conexao.dados_residuais = conexao.dados_residuais + dados
            dados = conexao.dados_residuais
        if dados.startswith(b'PING'):
            conexao.enviar(b':server PONG server :' + dados.split(b' ', 1)[1])

        print(conexao, dados)
        conexao.dados_residuais = None


def conexao_aceita(conexao):
    print(conexao, 'nova conexão')
    conexao.registrar_recebedor(dados_recebidos)


servidor = Servidor(6667)
servidor.registrar_monitor_de_conexoes_aceitas(conexao_aceita)
asyncio.get_event_loop().run_forever()
