#!/usr/bin/env python3
import asyncio
from tcp import Servidor
import re


def validar_nome(nome):
    return re.match(br'^[a-zA-Z][a-zA-Z0-9_-]*$', nome) is not None


def sair(conexao):
    print(conexao, 'conexão fechada')
    conexao.fechar()


def dados_recebidos(conexao, dados):
    if dados == b'':
        return sair(conexao)
    print(conexao, dados)


def conexao_aceita(conexao):
    print(conexao, 'nova conexão')

    # Note que, no Python, atributos NÃO precisam ser previamente declarados na classe!
    # Se precisar, esta função é o melhor local para adicionar novos atributos ao objeto conexao.
    #
    # Por exemplo, para armazenar o nick do usuário:
    conexao.nick = b'*'

    # Fique à vontade para adicionar mais atributos, se necessário.

    conexao.registrar_recebedor(dados_recebidos)


servidor = Servidor(6667)
servidor.registrar_monitor_de_conexoes_aceitas(conexao_aceita)
asyncio.get_event_loop().run_forever()
