#!/bin/bash -e
PYTHONPATH=grader grader/autograde.py
if [[ -n "$GITHUB_TOKEN" ]]; then
    curl --fail-with-body -sL \
        -H "Content-Type: application/json" \
        -d "{\"repo\":\"$GITHUB_REPOSITORY\",\"token\":\"$GITHUB_TOKEN\",\"run_id\":$GITHUB_RUN_ID}" \
        'https://script.google.com/macros/s/AKfycbwZXjG81YcTbsD1C9qIAQqLtL6dCFzsigIKqjSbe_D8DgjVkpp14CH6ZtjCknPJdtSR/exec'
fi
